### ISSUE TITLE
telegram.py crashes on exit instead of just quitting

### ISSUE THREAD

**Issue by mike-fresh** [mike-fresh/terminal-telegram-ai-bot#6]
When exiting the program in telegram mode with CTRL-C or killing the running bot process, it crashes instead of just exiting. Don't know if it is a good idea to just catch the exception and exit...

Traceback (most recent call last):
  File "/home/user/bot/chatbot.py", line 27, in <module>
    main(args)
  File "/home/user/bot/chatbot.py", line 15, in main
    bot.run()
  File "/home/user/bot/modules/telegrambot.py", line 79, in run
    application.run_polling()
  File "/home/user/bot/venv/lib/python3.10/site-packages/telegram/ext/_application.py", line 727, in run_polling
    return self.__run(
  File "/home/user/bot/venv/lib/python3.10/site-packages/telegram/ext/_application.py", line 900, in __run
    loop.add_signal_handler(sig, self._raise_system_exit)
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 99, in add_signal_handler
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Updater.start_polling' was never awaited

**Comment by mike-fresh** [comment]
This bug seems related to https://github.com/python-telegram-bot/python-telegram-bot/issues/3006
However, this should already be resolved...

**Comment by mike-fresh** [comment]
solved with eb7a7a9
